# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ee70c56e28aa9c560b475409d4f8dc24ac0b7ed4da043a4e722060794bcd061cbed4a0040f19e33928ab7441f5edb7071d92c11a23e48c9afa94c09aef70028

test:
  secret_key_base: 6c6a2892164771d33616b4619ec6fb975fa1c39082b9952cf7b3019102da883bf2b08991bb514b67ed16178e28e5a605fb7bab28c3ae2bc6f98324fb8624c95a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
